export const actionTypes = {
    GET_VEHICLES: "GET_VEHICLES",
    ADD_VEHICLE: "ADD_VEHICLE",
    UPDATE_VEHICLE: "UPDATE_VEHICLE",
    DELETE_VEHICLE: "DELETE_VEHICLE",
    GET_CUSTOMERS: "GET_CUSTOMERS",
    ADD_CUSTOMER: "ADD_CUSTOMER",
    UPDATE_CUSTOMER: "UPDATE_CUSTOMER",
    DELETE_CUSTOMER: "DELETE_CUSTOMER",
}