export const actionTypes = {
    ADD_VEHICLE: "ADD_VEHICLE",
    UPDATE_VEHICLE: "UPDATE_VEHICLE",
    DELETE_VEHICLE: "DELETE_VEHICLE",
    ADD_CUSTOMER: "ADD_CUSTOMER",
    UPDATE_CUSTOMER: "UPDATE_CUSTOMER",
    DELETE_CUSTOMER: "DELETE_CUSTOMER",
    ADD_VEHICLE_RENTAL: "ADD_VEHICLE_RENTAL",
    UPDATE_VEHICLE_RENTAL: "UPDATE_VEHICLE_RENTAL",
    DELETE_VEHICLE_RENTAL: "DELETE_VEHICLE_RENTAL",
}